apiVersion : apps/v1
kind: Deployment
metadata:
  name: privatechat 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privatechat
  template:
    metadata:
      labels:
        app: privatechat 
    spec:
      containers:
        - name: privatechat 
          image: registrodecotenedores.azurecr.io/privatechat
          ports:
          - containerPort: 12345